name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        echo "Deploying to server..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd /home/vmukti/ambicam
        ls -la && pwd

        if [ ! -d .git ]; then
          git init
        fi

        if ! git remote get-url origin &> /dev/null; then
          git remote add origin https://github.com/Rahulvmukti/Ambicam.git
          git remote set-url origin https://"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"@github.com/Rahulvmukti/Ambicam.git
        fi

        git remote -v
        EOF
